export const LOCALITIES = [
  "Green Park",
  "Gulmohar Park",
  "Hauz Khas",
  "Kalu Sarai",
  "Malviya Nagar",
  "Panchsheel Enclave",
  "Safdarjung Enclave",
  "Sarvapriya Vihar",
  "Vijay Mandal Enclave",
];

export const CATEGORIES = [
  { value: "apartment", label: "Apartment" },
  { value: "builder-floor", label: "Builder Floor" },
  { value: "independent-house", label: "Independent House" },
  { value: "studio", label: "Studio" },
  { value: "office", label: "Office Space" },
];

export const RENT_BUDGETS = [
  { value: "0-40000", label: "Under ₹40,000/mo" },
  { value: "40000-75000", label: "₹40,000 – ₹75,000/mo" },
  { value: "75000-125000", label: "₹75,000 – ₹1.25 L/mo" },
  { value: "125000-", label: "Above ₹1.25 L/mo" },
];

export const SALE_BUDGETS = [
  { value: "0-20000000", label: "Under ₹2 Cr" },
  { value: "20000000-50000000", label: "₹2 Cr – ₹5 Cr" },
  { value: "50000000-100000000", label: "₹5 Cr – ₹10 Cr" },
  { value: "100000000-", label: "Above ₹10 Cr" },
];

export const properties = [
  {
    "slug": "1-bhk-serviced-studio-safdarjung-enclave",
    "title": "1 BHK Serviced Studio in Safdarjung Enclave",
    "listingType": "rent",
    "category": "studio",
    "locality": "Safdarjung Enclave",
    "city": "New Delhi",
    "addressLine": "Safdarjung Enclave, near Arjun Nagar market",
    "price": 35000,
    "maintenance": 1500,
    "securityDeposit": 70000,
    "bedrooms": 1,
    "bathrooms": 1,
    "balconies": 1,
    "areaSqft": 620,
    "carpetAreaSqft": 540,
    "floor": "3rd of 4",
    "totalFloors": 4,
    "facing": "West",
    "furnishing": "fully-furnished",
    "ageYears": 4,
    "parking": "1 open (two-wheeler covered)",
    "availableFrom": "Immediate",
    "preferredTenants": "Single occupant / Couple",
    "amenities": [
      "Fully furnished studio layout",
      "Split AC",
      "Kitchenette with hob and chimney",
      "Fridge and microwave",
      "Housekeeping twice a week (included)",
      "Power backup",
      "High-speed fibre internet ready",
      "Lift"
    ],
    "highlights": [
      "Rent includes twice-weekly housekeeping",
      "Short lease from 6 months accepted — unusual for this pocket",
      "Walk to Arjun Nagar market, AIIMS and Green Park Metro nearby",
      "Perfect for a doctor, consultant or single professional on posting"
    ],
    "description": [
      "A compact, properly finished studio in Safdarjung Enclave, set up for someone who wants to arrive and start living the same day. The room is arranged as a sleeping area and a separate sitting corner, with a kitchenette along one wall and a balcony off the side.",
      "It comes fully furnished with a bed, wardrobe, work desk, sofa, split AC, fridge, microwave and a hob with chimney. Twice-weekly housekeeping is included in the rent, and the building is fibre-ready for high-speed internet.",
      "The owner will consider leases from six months, which is rare in this area and makes it a practical option for doctors at AIIMS or Safdarjung, consultants on a posting, or anyone who needs a good address without a long commitment."
    ],
    "images": [
      { "src": "/properties/bedroom-white.jpg", "alt": "Furnished studio sleeping area with double bed and side tables" },
      { "src": "/properties/interior-living-plants.jpg", "alt": "Studio sitting corner with sofa, plants and shelving" },
      { "src": "/properties/kitchen-modern.jpg", "alt": "Kitchenette with hob, chimney and fitted cabinets" }
    ],
    "badges": ["new"],
    "postedOn": "2026-08-01"
  },
  {
    "slug": "2-bhk-furnished-apartment-kalu-sarai",
    "title": "2 BHK Fully Furnished Apartment in Kalu Sarai",
    "listingType": "rent",
    "category": "apartment",
    "locality": "Kalu Sarai",
    "city": "New Delhi",
    "addressLine": "Kalu Sarai, opposite Sarvapriya Vihar",
    "price": 52000,
    "maintenance": 2000,
    "securityDeposit": 156000,
    "bedrooms": 2,
    "bathrooms": 2,
    "balconies": 1,
    "areaSqft": 1100,
    "carpetAreaSqft": 930,
    "floor": "1st of 4",
    "totalFloors": 4,
    "facing": "East",
    "furnishing": "fully-furnished",
    "ageYears": 8,
    "parking": "1 open",
    "availableFrom": "1 September 2026",
    "preferredTenants": "Family / Working professionals / Company lease",
    "amenities": [
      "Fully furnished — beds, sofas, dining, wardrobes",
      "Fridge, washing machine, microwave",
      "Split ACs in both bedrooms and living room",
      "Modular kitchen with chimney and hob",
      "Power backup",
      "Lift",
      "Water purifier",
      "Gated colony with guard"
    ],
    "highlights": [
      "Move-in ready — bring a suitcase and nothing else",
      "Company lease accepted, GST invoice available",
      "Two minutes from the Kalu Sarai main road and the IIT flyover",
      "Ideal for a couple, a small family, or two professionals sharing"
    ],
    "description": [
      "A genuinely move-in-ready 2 BHK in Kalu Sarai, furnished to a standard you can actually live with rather than the usual token bed-and-almirah. Both bedrooms have beds, mattresses, wardrobes and ACs; the living room has a sofa set, dining table and television unit.",
      "The kitchen is modular with a chimney, hob, fridge, microwave and RO purifier already installed, and there is a washing machine in the utility balcony. The colony is gated with a guard at the entrance, and the apartment sits on the first floor with lift access.",
      "Location is the strongest part of the deal: you are on Kalu Sarai, minutes from Hauz Khas, Green Park and Safdarjung Enclave, with the Outer Ring Road and the IIT flyover both within easy reach. Company leases are welcome and we can issue a GST invoice."
    ],
    "images": [
      { "src": "/properties/interior-living-bright.jpg", "alt": "Bright furnished living room with large windows and neutral sofas" },
      { "src": "/properties/interior-living-wood.jpg", "alt": "Living area with wood-panelled feature wall and open kitchen behind" },
      { "src": "/properties/kitchen-modern.jpg", "alt": "Modular kitchen with fitted appliances and a dining table" },
      { "src": "/properties/bedroom-white.jpg", "alt": "Furnished bedroom with double bed and fitted wardrobes" }
    ],
    "badges": ["verified"],
    "postedOn": "2026-07-30"
  },
  {
    "slug": "3-bhk-ground-floor-sarvapriya-vihar",
    "title": "3 BHK Ground Floor with Private Lawn, Sarvapriya Vihar",
    "listingType": "rent",
    "category": "builder-floor",
    "locality": "Sarvapriya Vihar",
    "city": "New Delhi",
    "addressLine": "Sarvapriya Vihar, near the community centre",
    "price": 95000,
    "maintenance": 2500,
    "securityDeposit": 285000,
    "bedrooms": 3,
    "bathrooms": 3,
    "balconies": 1,
    "areaSqft": 1750,
    "carpetAreaSqft": 1470,
    "floor": "Ground of 4",
    "totalFloors": 4,
    "facing": "South",
    "furnishing": "semi-furnished",
    "ageYears": 9,
    "parking": "1 covered in stilt",
    "availableFrom": "Immediate",
    "preferredTenants": "Family",
    "amenities": [
      "Private front lawn (~450 sq ft)",
      "Direct street entry — no stairs",
      "Modular kitchen",
      "Wardrobes in all bedrooms",
      "Power backup",
      "Piped gas",
      "Servant toilet",
      "Gated colony with guard",
      "Pet friendly"
    ],
    "highlights": [
      "Roughly 450 sq ft of private lawn — the reason ground floors here go quickly",
      "Step-free entry throughout, which suits older family members",
      "Landlord is genuinely pet friendly, confirmed in writing",
      "Two minutes from Sarvapriya Vihar community centre and market"
    ],
    "description": [
      "A ground-floor 3 BHK in Sarvapriya Vihar with its own front lawn of roughly 450 square feet — enclosed, private, and directly accessible from the drawing room. Ground floors with usable outdoor space are the first thing to go in this colony, and they rarely last a fortnight on the market.",
      "Inside, the floor is arranged with a wide drawing-dining at the front, three bedrooms with attached bathrooms behind, a modular kitchen with utility access, and a servant toilet at the rear. Entry is step-free from the street, which makes it a sensible choice for families with older parents.",
      "The colony is gated with a guard, the community centre and market are a two-minute walk, and our own office on Kalu Sarai is directly opposite the colony — so a viewing can usually be arranged within the hour. The landlord is confirmed pet friendly."
    ],
    "images": [
      { "src": "/properties/interior-living-blue.jpg", "alt": "Living room with blue sofa, television unit and garden-facing windows" },
      { "src": "/properties/interior-living-plants.jpg", "alt": "Sitting area with plants beside a window looking onto the lawn" },
      { "src": "/properties/bedroom-white.jpg", "alt": "Bedroom with fitted wardrobes and natural light" },
      { "src": "/properties/kitchen-modern.jpg", "alt": "Modular kitchen with hob, chimney and utility access" },
      { "src": "/properties/exterior-brick-wood.jpg", "alt": "Residential building frontage with landscaped ground-floor garden" }
    ],
    "badges": ["verified"],
    "postedOn": "2026-07-29"
  },
  {
    "slug": "4-bhk-independent-floor-vijay-mandal-enclave",
    "title": "4 BHK Independent Floor with Terrace, Vijay Mandal Enclave",
    "listingType": "sale",
    "category": "builder-floor",
    "locality": "Vijay Mandal Enclave",
    "city": "New Delhi",
    "addressLine": "Vijay Mandal Enclave, off Kalu Sarai main road",
    "price": 47500000,
    "negotiable": true,
    "bedrooms": 4,
    "bathrooms": 4,
    "balconies": 2,
    "areaSqft": 2400,
    "carpetAreaSqft": 2010,
    "floor": "3rd of 4 (top floor)",
    "totalFloors": 4,
    "facing": "North-East",
    "furnishing": "unfurnished",
    "ageYears": 2,
    "parking": "1 covered + stilt",
    "availableFrom": "Immediate",
    "amenities": [
      "Exclusive terrace rights",
      "Lift",
      "Modular kitchen",
      "Italian marble flooring",
      "VRV air conditioning provision",
      "Power backup",
      "Piped gas",
      "Video door phone",
      "Servant room with toilet",
      "Vaastu compliant"
    ],
    "highlights": [
      "Top floor with exclusive rights to a 900 sq ft terrace",
      "Freehold, single-owner, all approvals and completion certificate in place",
      "Two years old — still under builder's structural warranty",
      "Walking distance to our office on Kalu Sarai, so viewings are easy to arrange"
    ],
    "description": [
      "A top-floor 4 BHK in Vijay Mandal Enclave with exclusive terrace rights — the configuration South Delhi buyers look hardest for and find least often. The floor is two years old, built by a reputed local developer, and has been lightly used.",
      "Layout is generous and squared-off: a large drawing-dining running front to back, four bedrooms all with attached bathrooms, a modular kitchen with utility, and a servant room with separate toilet at the rear. Flooring is Italian marble in the living areas and wooden laminate in the bedrooms.",
      "The 900 sq ft terrace above is exclusively yours — enough for a landscaped sit-out, a solar setup, or an additional structure subject to sanction. Title is clean and freehold with a single owner, and the completion certificate is available for inspection."
    ],
    "images": [
      { "src": "/properties/exterior-brick-wood.jpg", "alt": "Contemporary brick and timber residential building exterior" },
      { "src": "/properties/interior-living-gallery.jpg", "alt": "Spacious living room with gallery wall and floor-to-ceiling windows" },
      { "src": "/properties/interior-dining-bay.jpg", "alt": "Formal dining area beside a bay window with garden views" },
      { "src": "/properties/bedroom-white.jpg", "alt": "Bedroom finished in white with wardrobes and natural light" },
      { "src": "/properties/terrace-pool.jpg", "alt": "Open terrace with glass doors and outdoor seating" }
    ],
    "badges": ["featured", "new"],
    "featured": true,
    "postedOn": "2026-07-28"
  },
  {
    "slug": "office-space-hauz-khas-village",
    "title": "2,200 sq ft Office Space in Hauz Khas Village",
    "listingType": "rent",
    "category": "office",
    "locality": "Hauz Khas",
    "city": "New Delhi",
    "addressLine": "Hauz Khas Village, near the Deer Park entrance",
    "price": 185000,
    "maintenance": 12000,
    "securityDeposit": 1110000,
    "bedrooms": 0,
    "bathrooms": 3,
    "areaSqft": 2200,
    "carpetAreaSqft": 1850,
    "floor": "2nd of 3",
    "totalFloors": 3,
    "facing": "North",
    "furnishing": "semi-furnished",
    "ageYears": 5,
    "parking": "3 reserved + street",
    "availableFrom": "15 September 2026",
    "preferredTenants": "Studios, agencies, consultancies, small tech teams",
    "amenities": [
      "Open-plan floor plate with two cabins",
      "Conference room with glass partition",
      "Pantry and three washrooms",
      "Full power backup",
      "Fibre internet from two providers",
      "Passenger lift",
      "Split ACs installed",
      "24x7 access"
    ],
    "highlights": [
      "Rare full-floor plate in Hauz Khas Village with genuine natural light",
      "Seats roughly 40 in an open layout, plus two cabins and a conference room",
      "Three reserved parking bays — the scarcest commodity in HKV",
      "Registered lease with GST invoicing; landlord is open to a 5-year term"
    ],
    "description": [
      "A full second-floor plate in Hauz Khas Village, laid out as an open working floor with two cabins and a glass-partitioned conference room at one end. Windows run along two sides, so the floor gets real daylight rather than the borrowed light most HKV offices settle for.",
      "The space seats roughly forty people comfortably in an open plan. It comes with a pantry, three washrooms, split ACs already installed, full power backup and fibre connections available from two providers. Access is 24x7, which matters for studios and teams that keep irregular hours.",
      "Three reserved parking bays come with the lease — worth noting, because parking is the single hardest thing to secure in this area. The landlord prefers a registered lease and is open to a five-year term with a standard escalation. GST invoicing is available."
    ],
    "images": [
      { "src": "/properties/architecture-curve.jpg", "alt": "Curved contemporary building facade against a clear sky" },
      { "src": "/properties/city-towers.jpg", "alt": "Commercial office towers viewed from street level" },
      { "src": "/properties/interior-stairwell.jpg", "alt": "Open stairwell and landing serving the office floor" },
      { "src": "/properties/city-street.jpg", "alt": "Busy commercial street with shops and offices" }
    ],
    "badges": ["featured", "verified"],
    "featured": true,
    "postedOn": "2026-07-25"
  },
  {
    "slug": "3-bhk-builder-floor-hauz-khas",
    "title": "3 BHK Builder Floor in Hauz Khas",
    "listingType": "rent",
    "category": "builder-floor",
    "locality": "Hauz Khas",
    "city": "New Delhi",
    "addressLine": "Block C, Hauz Khas Enclave, near Deer Park",
    "price": 110000,
    "maintenance": 3000,
    "securityDeposit": 330000,
    "bedrooms": 3,
    "bathrooms": 3,
    "balconies": 2,
    "areaSqft": 1800,
    "carpetAreaSqft": 1520,
    "floor": "2nd of 4",
    "totalFloors": 4,
    "facing": "Park facing (East)",
    "furnishing": "semi-furnished",
    "ageYears": 6,
    "parking": "1 covered + 1 open",
    "availableFrom": "Immediate",
    "preferredTenants": "Family / Working professionals",
    "amenities": [
      "Lift",
      "100% power backup",
      "Modular kitchen",
      "Piped gas",
      "Wardrobes in all bedrooms",
      "Split ACs installed",
      "Geysers",
      "Intercom & CCTV at entrance",
      "24x7 water supply",
      "Servant toilet"
    ],
    "highlights": [
      "Directly overlooks Deer Park — quiet, green and rare in this pocket",
      "Six-minute walk to Hauz Khas Metro (Magenta & Yellow lines)",
      "Lift lands on your private landing — no shared lobby",
      "Landlord is flexible on light interior changes for a 3-year lease"
    ],
    "description": [
      "A bright, well-proportioned 3 BHK floor on a quiet residential street in Hauz Khas Enclave, with the green edge of Deer Park directly across the road. The drawing and dining run the full width of the front, opening onto a deep balcony that catches morning sun.",
      "All three bedrooms are genuine double rooms with fitted wardrobes and attached bathrooms. The kitchen is modular with a utility balcony behind it, and there is a separate servant toilet off the rear passage. The building has a lift, full power backup, and a single family per floor.",
      "It suits a family or a group of working professionals who want space and quiet without leaving central South Delhi. Hauz Khas Metro, Green Park market and IIT Delhi are all within a short drive, and the Outer Ring Road is two minutes away."
    ],
    "images": [
      { "src": "/properties/interior-living-dining.jpg", "alt": "Sunlit drawing and dining area with large windows and light wood flooring" },
      { "src": "/properties/interior-living-plants.jpg", "alt": "Seating area with plants and open shelving beside a bright window" },
      { "src": "/properties/bedroom-white.jpg", "alt": "Master bedroom with fitted wardrobes and a large window" },
      { "src": "/properties/kitchen-modern.jpg", "alt": "Modular kitchen with dark cabinetry and a dining table alongside" },
      { "src": "/properties/interior-stairwell.jpg", "alt": "Private staircase landing leading up to the second floor entrance" }
    ],
    "badges": ["featured", "verified"],
    "featured": true,
    "postedOn": "2026-07-22"
  },
  {
    "slug": "3-bhk-apartment-green-park-extension",
    "title": "3 BHK Apartment in Green Park Extension",
    "listingType": "sale",
    "category": "apartment",
    "locality": "Green Park",
    "city": "New Delhi",
    "addressLine": "Green Park Extension, near Aurobindo Marg",
    "price": 36000000,
    "negotiable": true,
    "bedrooms": 3,
    "bathrooms": 3,
    "balconies": 2,
    "areaSqft": 1650,
    "carpetAreaSqft": 1390,
    "floor": "2nd of 4",
    "totalFloors": 4,
    "facing": "South-East",
    "furnishing": "semi-furnished",
    "ageYears": 12,
    "parking": "1 covered",
    "availableFrom": "Immediate",
    "amenities": [
      "Lift",
      "Power backup",
      "Modular kitchen",
      "Wardrobes",
      "Piped gas",
      "24x7 water supply",
      "Visitor parking",
      "Park within the colony",
      "Metro within 900 m"
    ],
    "highlights": [
      "Freehold with a clean, single-owner title",
      "900 m from Green Park Metro on the Yellow Line",
      "AIIMS, Safdarjung Hospital and Aurobindo Marg all within 10 minutes",
      "Well-maintained building with an active RWA and reliable backup"
    ],
    "description": [
      "A well-kept 3 BHK on the second floor of a small, established building in Green Park Extension — one of the most consistently in-demand addresses in South Delhi, and one where resale inventory rarely stays on the market long.",
      "The apartment has a long drawing-dining with a balcony at each end, three bedrooms with attached bathrooms and fitted wardrobes, and a modular kitchen with a utility area. It has been maintained carefully by the current owner and needs no structural work — at most, a cosmetic refresh to taste.",
      "The building has a lift, dependable power backup and covered parking, and the RWA is active about upkeep. Green Park Metro is a nine-hundred-metre walk, and AIIMS, Safdarjung Hospital, IIT Delhi and Aurobindo Marg are each within ten minutes by car."
    ],
    "images": [
      { "src": "/properties/exterior-apartment-block.jpg", "alt": "Low-rise residential apartment building with balconies" },
      { "src": "/properties/interior-living-grey.jpg", "alt": "Living room with grey sofas, fireplace and built-in shelving" },
      { "src": "/properties/interior-dining-bay.jpg", "alt": "Dining area beside a bay window" },
      { "src": "/properties/bedroom-white.jpg", "alt": "Bedroom with wardrobes and a wide window" },
      { "src": "/properties/kitchen-modern.jpg", "alt": "Modular kitchen with fitted cabinetry" }
    ],
    "badges": ["featured", "verified"],
    "featured": true,
    "postedOn": "2026-07-18"
  },
  {
    "slug": "5-bhk-independent-house-panchsheel-enclave",
    "title": "5 BHK Independent House in Panchsheel Enclave",
    "listingType": "sale",
    "category": "independent-house",
    "locality": "Panchsheel Enclave",
    "city": "New Delhi",
    "addressLine": "Panchsheel Enclave, near Panchsheel Park",
    "price": 125000000,
    "negotiable": true,
    "bedrooms": 5,
    "bathrooms": 6,
    "balconies": 4,
    "areaSqft": 4500,
    "carpetAreaSqft": 3750,
    "floor": "Full house (G+2)",
    "totalFloors": 3,
    "facing": "Park facing (East)",
    "furnishing": "semi-furnished",
    "ageYears": 7,
    "parking": "4 covered",
    "availableFrom": "Immediate",
    "amenities": [
      "Entire independent house on a 400 sq yd plot",
      "Private lift serving all three floors",
      "Landscaped front lawn and rear terrace",
      "Home automation and central air conditioning",
      "Two servant rooms with toilets",
      "Full power backup with DG",
      "CCTV and boundary security",
      "Modular kitchen plus separate service kitchen",
      "Vaastu compliant"
    ],
    "highlights": [
      "Whole house on a 400 sq yd freehold plot — no shared ownership",
      "Private lift across all three floors, plus four covered car parks",
      "Park frontage in one of the tightest-held colonies in South Delhi",
      "Seven years old and immaculately maintained by a single family"
    ],
    "description": [
      "An entire independent house on a 400 square yard freehold plot in Panchsheel Enclave, facing the colony park. Properties of this size and tenure almost never reach the open market here — they change hands quietly, usually within the neighbourhood.",
      "The house runs over ground plus two floors, served by a private lift. There are five bedrooms, all en-suite, plus a powder room, a formal drawing room, a separate family lounge, a modular kitchen with a service kitchen behind it, and two servant rooms with their own toilets. Air conditioning is central and the house is wired for home automation.",
      "Outside there is a landscaped front lawn, a rear terrace on the top floor, and covered parking for four cars behind the boundary wall. It has been owned and maintained by a single family since it was built seven years ago, and the condition reflects that. Title is freehold and clean."
    ],
    "images": [
      { "src": "/properties/exterior-villa-dusk.jpg", "alt": "Independent house lit at dusk with landscaped garden and pool" },
      { "src": "/properties/exterior-house-pool.jpg", "alt": "House frontage with mature planting and covered parking" },
      { "src": "/properties/exterior-brick-modern.jpg", "alt": "Contemporary elevation of the house viewed from the garden" },
      { "src": "/properties/interior-living-green.jpg", "alt": "Formal drawing room with tan sofas and a green feature wall" },
      { "src": "/properties/terrace-pool.jpg", "alt": "Rear terrace with glass doors and outdoor seating" },
      { "src": "/properties/interior-stairwell.jpg", "alt": "Central staircase and private lift lobby" }
    ],
    "badges": ["featured", "verified"],
    "featured": true,
    "postedOn": "2026-07-15"
  },
  {
    "slug": "4-bhk-luxury-builder-floor-gulmohar-park",
    "title": "4 BHK Luxury Builder Floor in Gulmohar Park",
    "listingType": "sale",
    "category": "builder-floor",
    "locality": "Gulmohar Park",
    "city": "New Delhi",
    "addressLine": "Gulmohar Park, off Aurobindo Marg",
    "price": 62500000,
    "negotiable": false,
    "bedrooms": 4,
    "bathrooms": 4,
    "balconies": 3,
    "areaSqft": 2800,
    "carpetAreaSqft": 2340,
    "floor": "1st of 4",
    "totalFloors": 4,
    "facing": "Park facing (North)",
    "furnishing": "semi-furnished",
    "ageYears": 3,
    "parking": "2 covered",
    "availableFrom": "Immediate",
    "amenities": [
      "Park facing across the full frontage",
      "Private lift lobby",
      "Imported marble and oak flooring",
      "VRV air conditioning",
      "Modular kitchen with island",
      "100% power backup",
      "Servant room with separate entry",
      "Video door phone & CCTV",
      "Piped gas",
      "Vaastu compliant"
    ],
    "highlights": [
      "Full-width park frontage — light and green from every front room",
      "Two covered car parks, which is genuinely scarce in Gulmohar Park",
      "Built three years ago to a specification well above the local norm",
      "Freehold, clean title, ready for immediate registry"
    ],
    "description": [
      "Gulmohar Park is one of the quietest and most established colonies in South Delhi, and this first-floor apartment takes proper advantage of it — the entire front elevation faces the colony park, so the drawing room, dining and two of the four bedrooms look out onto mature trees.",
      "Specification is a clear step above the usual builder floor: imported marble in the living areas, oak flooring in the bedrooms, VRV air conditioning throughout, a modular kitchen with an island, and a private lift lobby so you step out of the lift into your own entrance rather than a shared landing.",
      "There are four bedrooms, all en-suite, plus a servant room with a separate service entry. Two covered car parks come with the floor. The property is freehold with a clean title and is ready for immediate registry."
    ],
    "images": [
      { "src": "/properties/exterior-modern-garden.jpg", "alt": "Modern residential building exterior with landscaped garden frontage" },
      { "src": "/properties/interior-living-green.jpg", "alt": "Formal living room with tan leather sofas and a green feature wall" },
      { "src": "/properties/interior-living-gallery.jpg", "alt": "Second sitting room with tall windows and curated artwork" },
      { "src": "/properties/terrace-pool.jpg", "alt": "Balcony sit-out with glass sliding doors overlooking the park" },
      { "src": "/properties/interior-stairwell.jpg", "alt": "Private lift lobby and staircase finished in stone" }
    ],
    "badges": ["featured"],
    "featured": true,
    "postedOn": "2026-07-12"
  },
  {
    "slug": "2-bhk-apartment-malviya-nagar",
    "title": "2 BHK Apartment in Malviya Nagar",
    "listingType": "sale",
    "category": "apartment",
    "locality": "Malviya Nagar",
    "city": "New Delhi",
    "addressLine": "Malviya Nagar, near the main market",
    "price": 15500000,
    "negotiable": true,
    "bedrooms": 2,
    "bathrooms": 2,
    "balconies": 1,
    "areaSqft": 950,
    "carpetAreaSqft": 800,
    "floor": "2nd of 4",
    "totalFloors": 4,
    "facing": "East",
    "furnishing": "unfurnished",
    "ageYears": 15,
    "parking": "1 open",
    "availableFrom": "Immediate",
    "amenities": [
      "Lift",
      "Power backup",
      "Piped gas",
      "24x7 water supply",
      "Metro within 700 m",
      "Market within walking distance"
    ],
    "highlights": [
      "Sensible entry point into South Delhi ownership under ₹2 Cr",
      "700 m from Malviya Nagar Metro on the Yellow Line",
      "Currently rented at ₹28,000 — can be sold with the tenant in place",
      "Freehold with a clear title and no outstanding dues"
    ],
    "description": [
      "A practical 2 BHK in Malviya Nagar, well suited to a first purchase in South Delhi or to an investor who wants a yielding asset in a location that always rents. The apartment is on the second floor of a four-storey building with a lift.",
      "The layout is efficient: a drawing-dining at the front with a balcony, two bedrooms with attached bathrooms, and a separate kitchen. It is unfurnished and fifteen years old, so budget for a cosmetic refresh — the structure, plumbing and wiring are all sound.",
      "It is currently let at ₹28,000 a month to a long-standing tenant, and the seller is open to transferring it with the tenancy in place. Malviya Nagar Metro is a seven-hundred-metre walk, and the main market, Select Citywalk and Saket are all close by. Title is freehold and clear."
    ],
    "images": [
      { "src": "/properties/interior-living-wood.jpg", "alt": "Living area with wood-panelled wall and adjoining kitchen" },
      { "src": "/properties/interior-living-bright.jpg", "alt": "Bright drawing room with large windows" },
      { "src": "/properties/kitchen-modern.jpg", "alt": "Kitchen with fitted cabinetry and counter space" },
      { "src": "/properties/bedroom-white.jpg", "alt": "Bedroom with window and wardrobe space" }
    ],
    "badges": [],
    "postedOn": "2026-07-08"
  }
];
